"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# Application definition

INSTALLED_APPS = [
    # 'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "corsheaders",
    "drf_spectacular",
    "django_celery_beat",
    "django_prometheus",

    "apps.accounts.apps.AccountsConfig",
    "apps.site_setting.apps.SiteSettingConfig",
    "apps.customers.apps.CustomersConfig",
    "apps.admins.apps.SiteAdminsConfig",
    "apps.notifications.apps.NotificationsConfig",
    "apps.exchange.apps.ExchangeConfig",
    "apps.payments.apps.PaymentsConfig"
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": dj_database_url.config(
#         default=config(
#             "DATABASE_URL",
#             default="sqlite:///db.sqlite3",
#         ),
#         conn_max_age=600,
#     )
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": config('DATABASE_HOST'),
        "PORT": config('DATABASE_PORT'),
        "NAME": config('DATABASE_NAME'),
        "USER": config('DATABASE_USER'),
        "PASSWORD": config('DATABASE_PASSWORD'),
    }
}

# Cache
REDIS_HOST = config("REDIS_HOST")
REDIS_PORT = config("REDIS_PORT", cast=int)
REDIS_DB = config("REDIS_DB", cast=int)
REDIS_PASS = config("REDIS_PASS", default="")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://:{REDIS_PASS}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

CACHES["otp"] = {
    "BACKEND": "django_redis.cache.RedisCache",
    "LOCATION": f"redis://:{REDIS_PASS}@{REDIS_HOST}:{REDIS_PORT}/1",
    "OPTIONS": {
        "CLIENT_CLASS": "django_redis.client.DefaultClient",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = "/media/"

STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "media"


STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication model
AUTH_USER_MODEL = "accounts.CustomUser"

# Rest framework settings
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "apps.core.exceptions.handler.custom_exception_handler",
    "DEFAULT_PAGINATION_CLASS": "apps.core.pagination.StandardResultsSetPagination",
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
    "DEFAULT_PERMISSION_CLASSES": (),
}

# JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": config("SECRET_KEY"),
}

# Drf spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'Im a NINJA too 🥷',
    'DESCRIPTION': 'Gold Trading Paltfrom Docs',
    'VERSION': '1.0.0',

    'COMPONENT_SPLIT_REQUEST': True,
    "SWAGGER_UI_DIST": "/static/drf_spectacular/",

    "CONTACT": {
        "name": "Website Developer",
        "email": "esi.taheri@yahoo.com",
        "url": "https://linkedin.com/"
    },

    "LICENSE": {
        "name": "MIT License",
        "url": "https://opensource.org/licenses/MIT"
    },

    "TAGS": [
        {"name": "Accounts", "description": "User-related endpoints"},
        {"name": "Notifications", "description": "Notification-related endpoints"},
        {"name": "Customers", "description": "Customer-related endpoints"},
        {"name": "Exchange", "description": "Exchange-related endpoints"},
        {"name": "schema", "description": "Schema-related endpoints"},
    ]
}

# sms provider
SMS_IR_API_KEY = config('SMS_IR_API_KEY') #SND
SEND_LOGIN_OTP_TEMPLATE_ID = config('SEND_LOGIN_OTP_TEMPLATE_ID')
SEND_MESSAGE_TEMPLATE_ID = config('SEND_MESSAGE_TEMPLATE_ID')

# Inquiry service
INQUIRY_SERVICE_USERNAME = config('INQUIRY_SERVICE_USERNAME')
INQUIRY_SERVICE_PASSWORD = config('INQUIRY_SERVICE_PASSWORD')

# Object storage credentials
OBJECT_STORAGE_ACCESS_KEY = config('OBJECT_STORAGE_ACCESS_KEY')
OBJECT_STORAGE_SECRET_KEY = config('OBJECT_STORAGE_SECRET_KEY')
OBJECT_STORAGE_ENDPOINT_URL = config('OBJECT_STORAGE_ENDPOINT_URL')
OBJECT_STORAGE_SECURE = False  # True when https

# Celery
CELERY_TIMEZONE = 'Asia/Tehran'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'
CELERY_TASK_IGNORE_RESULT = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_URL = config('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = config('CELERY_BROKER_URL')


# Jazzmin

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-lime",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",  # بهترین دارک بالانس شده
    "dark_mode_theme": "cyborg",
    "default_theme_mode": "dark",

    # ---------- Buttons ----------
    "button_classes": {
        "primary": "btn-outline-cyan",
        "secondary": "btn-outline-light",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
}

JAZZMIN_SETTINGS = {
    "site_title": "Admin Panel",
    "site_header": "Finance Dashboard",
    "site_brand": "⚡ Core Admin",
    "welcome_sign": "Welcome to Control Center",

    "icons": {

        # Dashboard
        "auth": "fas fa-gauge-high",

        # Accounts
        "accounts.CustomUser": "fas fa-user",

        # Admins
        "admins.SiteAdmin": "fas fa-user-shield",
        "admins.TrustedIp": "fas fa-shield-halved",

        # Authentication
        "auth.Group": "fas fa-users",

        # Customers
        "customers.Customer": "fas fa-user-tag",
        "customers.BankCard": "fas fa-credit-card",
        "customers.KYC": "fas fa-id-card",
        "customers.IncreaseDailyTransactionLimit": "fas fa-arrow-up-right-dots",

        # Exchange
        "exchange.Currency": "fas fa-coins",
        "exchange.CurrencyBalance": "fas fa-wallet",
        "exchange.CurrencyPriceLog": "fas fa-chart-line",
        "exchange.DailyTransactionLimit": "fas fa-tachometer-alt",
        "exchange.Transaction": "fas fa-arrow-right-arrow-left",
        "exchange.Wallet": "fas fa-wallet",

        # Notifications
        "notifications.NotificationTemplate": "fas fa-envelope-open-text",
        "notifications.Notification": "fas fa-bell",
        "notifications.UserNotificationStatus": "fas fa-user-check",

        # Celery Beat
        "django_celery_beat.ClockedSchedule": "fas fa-clock",
        "django_celery_beat.CrontabSchedule": "fas fa-calendar-days",
        "django_celery_beat.IntervalSchedule": "fas fa-hourglass-half",
        "django_celery_beat.PeriodicTask": "fas fa-rotate",
        "django_celery_beat.SolarSchedule": "fas fa-sun",

        # Site Setting
        "site_setting.SiteSetting": "fas fa-gears",
    }

}
