# Generated by Django 5.2.11 on 2026-04-10 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('ip', models.GenericIPAddressField(verbose_name='IP Address')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_otp_enabled', models.BooleanField(default=False, verbose_name='Enabled OTP')),
                ('nick_name', models.CharField(max_length=100, verbose_name='Nickname')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('about', models.TextField(blank=True, verbose_name='About')),
                ('personal_code', models.CharField(max_length=4, unique=True, verbose_name='Personal Code')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='admins/admin_profile_pics/', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('allowed_ips', models.ManyToManyField(blank=True, to='admins.trustedip', verbose_name='Allowed IPs')),
            ],
        ),
    ]
