# Generated by Django 5.2.11 on 2026-04-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteadmin',
            name='profile_pic',
            field=models.URLField(default='-', verbose_name='Profile Picture'),
        ),
    ]
