# Generated by Django 5.2.11 on 2026-04-15 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0002_alter_siteadmin_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('fa_title', models.CharField(max_length=50, verbose_name='Frasi Title')),
                ('en_title', models.CharField(max_length=50, verbose_name='English Title')),
                ('logo_url', models.URLField(verbose_name='Logo Url')),
                ('about', models.TextField(blank=True, verbose_name='About')),
                ('lowest_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Lowest Amount Can Buy')),
                ('buy_fee', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Buy Fee')),
                ('sell_fee', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Sell Fee')),
                ('is_sell', models.BooleanField(default=False, verbose_name='Buy Is Enabled')),
                ('is_buy', models.BooleanField(default=False, verbose_name='Sell Is Enabled')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Locked Balance')),
                ('locked_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Locked Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange.currency', verbose_name='Currency')),
                ('modified_by', models.ManyToManyField(blank=True, to='admins.siteadmin', verbose_name='Modified By')),
            ],
        ),
    ]
