# Generated by Django 5.2.11 on 2026-04-15 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencybalance',
            name='active_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Active Balance'),
        ),
        migrations.AlterField(
            model_name='currencybalance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='currencybalance',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified At'),
        ),
        migrations.CreateModel(
            name='CurrencyPriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('timestamp', models.IntegerField(default=0, verbose_name='Timestamp')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='exchange.currency', verbose_name='Currency')),
            ],
        ),
    ]
