# Generated by Django 5.2.11 on 2026-04-15 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_siteadmin_profile_pic'),
        ('customers', '0004_alter_bankcard_is_verified_and_more'),
        ('exchange', '0002_alter_currencybalance_active_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('irt', 'Toman'), ('xau', 'Gold')], default='irt', max_length=3, verbose_name='Wallet Type')),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Amount')),
                ('desc', models.CharField(blank=True, max_length=350, verbose_name='Description')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Is Rejected')),
                ('reject_reson', models.CharField(blank=True, max_length=350, verbose_name='Rejected Reason')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='Ip Address')),
                ('created_at', models.BigIntegerField(verbose_name='Created at Timestamp')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='customers.customer', verbose_name='Customer')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.siteadmin', verbose_name='Modified By')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Amount')),
                ('fee_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Fee')),
                ('fee_irt', models.BigIntegerField(default=0, verbose_name='Fee IRT')),
                ('unit_price_irt', models.BigIntegerField(default=0, verbose_name='Unit Price IRT')),
                ('total_price_irt', models.BigIntegerField(default=0, verbose_name='Total Price IRT')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='Ip Address')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=10, verbose_name='Transaction Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('gateway_buy', models.BooleanField(default=False, verbose_name='Gateway Buy')),
                ('created_at', models.BigIntegerField(default=0, verbose_name='Created At')),
                ('processed_at', models.BigIntegerField(default=0, verbose_name='Processed At')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='exchange.currency', verbose_name='currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customer', verbose_name='Customer')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='exchange.wallet', verbose_name='Wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['customer'], name='exchange_wa_custome_17f2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['wallet_type'], name='exchange_wa_wallet__ea71e6_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['is_verified'], name='exchange_wa_is_veri_d83e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['is_rejected'], name='exchange_wa_is_reje_9275f1_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['created_at'], name='exchange_wa_created_d59075_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='exchange_tr_status_4f19f0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='exchange_tr_transac_d4b386_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='exchange_tr_created_f528e0_idx'),
        ),
    ]
