# Generated by Django 5.2.11 on 2026-04-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_wallet_transaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='lowest_amount',
            new_name='lowest_amount_buy',
        ),
        migrations.AddField(
            model_name='currency',
            name='lowest_amount_sell',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Lowest Amount Can Sell'),
        ),
    ]
