# Generated by Django 5.2.11 on 2026-04-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_rename_lowest_amount_currency_lowest_amount_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='maintance_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Buy Fee'),
        ),
    ]
