# Generated by Django 5.2.11 on 2026-04-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_currency_maintance_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='buy_fee',
            new_name='buy_fee_percent',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='sell_fee',
        ),
        migrations.AddField(
            model_name='currency',
            name='max_buy_fee_percent',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Maximum Buy Fee'),
        ),
        migrations.AddField(
            model_name='currency',
            name='max_sell_fee_percent',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Maximum Sell Fee'),
        ),
        migrations.AddField(
            model_name='currency',
            name='min_buy_fee_percent',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Minimum Buy Fee'),
        ),
        migrations.AddField(
            model_name='currency',
            name='min_sell_fee_percent',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Minimum Sell Fee'),
        ),
        migrations.AddField(
            model_name='currency',
            name='sell_fee_percent',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='sell Fee'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='maintance_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Maintance Fee'),
        ),
    ]
