# Generated by Django 5.2.11 on 2026-04-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_rename_buy_fee_currency_buy_fee_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='max_buy_fee_percent',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='max_sell_fee_percent',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='min_buy_fee_percent',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='min_sell_fee_percent',
        ),
        migrations.AddField(
            model_name='currency',
            name='fixed_buy_fee_toman',
            field=models.BigIntegerField(default=0, verbose_name='Fixed Buy Fee Toman'),
        ),
        migrations.AddField(
            model_name='currency',
            name='fixed_sell_fee_toman',
            field=models.BigIntegerField(default=0, verbose_name='Fixed Sell Fee Toman'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='buy_fee_percent',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Buy Fee '),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sell_fee_percent',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Sell Fee '),
        ),
    ]
