# Generated by Django 5.2.11 on 2026-04-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_remove_currency_max_buy_fee_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='is_buy',
            field=models.BooleanField(default=False, verbose_name='Buy Is Enabled'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_sell',
            field=models.BooleanField(default=False, verbose_name='Sell Is Enabled'),
        ),

        migrations.RunSQL(
            sql="""
                ALTER TABLE exchange_wallet
                ALTER COLUMN verified_at
                TYPE bigint
                USING EXTRACT(EPOCH FROM verified_at);
            """,
            reverse_sql="""
                ALTER TABLE exchange_wallet
                ALTER COLUMN verified_at
                TYPE timestamp with time zone
                USING to_timestamp(verified_at);
            """
        ),

        migrations.AlterField(
            model_name='wallet',
            name='verified_at',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Verified At'),
        ),
    ]
