# Generated by Django 5.2.11 on 2026-04-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_siteadmin_profile_pic'),
        ('exchange', '0008_alter_currency_is_buy_alter_currency_is_sell_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTransactionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_amount', models.BigIntegerField(default=0, verbose_name='Buy Limit')),
                ('sell_amount', models.BigIntegerField(default=0, verbose_name='Sell Limit')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.siteadmin', verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
