# Generated by Django 5.2.11 on 2026-04-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_dailytransactionlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='buy_from_gateway',
            field=models.BooleanField(default=False, verbose_name='Buy From Gateway'),
        ),
        migrations.AddField(
            model_name='currency',
            name='buy_from_wallet',
            field=models.BooleanField(default=False, verbose_name='Buy From Wallet'),
        ),
    ]
