# Generated by Django 5.2.11 on 2026-05-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_currency_buy_from_gateway_currency_buy_from_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='gateway_buy',
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('bank', 'Bank')], default='wallet', max_length=10, verbose_name='Deposit Method'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Checked'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reject_reason',
            field=models.CharField(default='', max_length=255, verbose_name='Reject Reason'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdraw_method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('gate', 'Gateway')], default='wallet', max_length=10, verbose_name='Withdraw Method'),
        ),
    ]
