# Generated by Django 5.2.11 on 2026-05-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_remove_transaction_gateway_buy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='deposit_method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('gate', 'Gateway')], default='wallet', max_length=10, verbose_name='Deposit Method'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='withdraw_method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('bank', 'Bank')], default='wallet', max_length=10, verbose_name='Withdraw Method'),
        ),
    ]
