# Generated by Django 5.2.11 on 2026-05-13 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_alter_transaction_deposit_method_and_more'),
        ('payments', '0005_invoice_is_processed_invoice_processed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='payments.invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='exchange.wallet', verbose_name='Wallet'),
        ),
    ]
