# Generated by Django 5.2.11 on 2026-05-13 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_bankcard_reject_reason'),
        ('exchange', '0013_transaction_invoice_alter_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='customers.bankcard', verbose_name='Bank Card'),
        ),
    ]
