# Generated by Django 5.2.11 on 2026-05-09 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_increasedailytransactionlimit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway', models.CharField(blank=True, max_length=255, verbose_name='Payment Gateway')),
                ('gateway_tack_id', models.CharField(blank=True, max_length=255, verbose_name='Gateway Track ID')),
                ('gateway_response', models.TextField(blank=True, verbose_name='Gateway Response')),
                ('unit_price', models.BigIntegerField(default=0, verbose_name='Unit Price')),
                ('fee', models.IntegerField(default=0, verbose_name='Fee')),
                ('maintenance_fee', models.IntegerField(default=0, verbose_name='Maintenance Fee')),
                ('total_price', models.BigIntegerField(default=0, verbose_name='Total Price')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.customer', verbose_name='Customer')),
            ],
        ),
    ]
