# Generated by Django 5.2.11 on 2026-05-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_invoice_options_invoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='card_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='Card Hash'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='card_pan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Card PAN'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Reference ID'),
        ),
    ]
