# Generated by Django 5.2.11 on 2026-05-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_invoice_card_hash_invoice_card_pan_invoice_ref_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='gateway_tack_id',
            new_name='gateway_track_id',
        ),
    ]
