# Generated by Django 5.2.11 on 2026-05-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_gateway_tack_id_invoice_gateway_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Is Processed'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processed At'),
        ),
    ]
