services:
  db:
    image: postgres:16
    container_name: django_postgres
    restart: unless-stopped
    env_file:
    - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - django_postgres_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - django_network

  redis:
    image: redis:7
    container_name: django_redis
    restart: always

    env_file:
      - .env

    command: ["redis-server", "--requirepass", "${REDIS_PASS}"]

    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "PING"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

    networks:
      - django_network

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: django_backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout 120 --access-logfile - --error-logfile -
    env_file:
      - .env
    environment:
      HOME: /tmp
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      ACCESS_TOKEN_LIFETIME_DAYS: ${ACCESS_TOKEN_LIFETIME_DAYS}
      REFRESH_TOKEN_LIFETIME_DAYS: ${REFRESH_TOKEN_LIFETIME_DAYS}
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - django_network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/api/health/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    command: celery -A config worker --loglevel=INFO -E
    environment:
      - PYTHONPATH=/app/src
      - DJANGO_SETTINGS_MODULE=config.settings.base
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend

    networks:
      - django_network

  celery_beat:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - PYTHONPATH=/app/src
      - DJANGO_SETTINGS_MODULE=config.settings.base
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend
    networks:
      - django_network

  flower:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: django_flower
    command: celery -A config flower --port=5555
    ports:
      - "5555:5555"
    environment:
      PYTHONPATH: /app/src
      DJANGO_SETTINGS_MODULE: config.settings.base
    env_file:
      - .env
    depends_on:
      - redis
      - celery
    networks:
      - django_network

  prometheus:
      image: prom/prometheus
      container_name: prometheus
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"
      depends_on:
        - backend
      networks:
        - django_network

  grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3000:3000"
      volumes:
        - grafana-storage:/var/lib/grafana
      environment:
        - GF_INSTALL_PLUGINS=
        - GF_PLUGINS_PREINSTALL=
      depends_on:
        - prometheus
      networks:
        - django_network

  nginx:
    image: nginx:mainline-alpine3.23
    container_name: django_nginx
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    # depends_on:
    #   backend:
    #     condition: service_healthy
    networks:
      - django_network

volumes:
  django_postgres_data:
  grafana-storage:

networks:
  django_network:
    driver: bridge
