# Worker
worker_processes auto;


events {}


# Backend
http {
    # Resolver
    resolver 127.0.0.11 valid=30s;

    # MIME Types
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    # Rate Limit
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=login_limit:10m rate=5r/m;
    limit_req_status 429;

    server {
        listen 80;
        server_name localhost;

        keepalive_timeout 65;

        access_log /var/log/nginx/api_access.log;
        error_log  /var/log/nginx/api_error.log warn;

        add_header X-Frame-Options "DENY" always;

        proxy_buffering off;
        proxy_request_buffering off;

        set $backend_upstream backend:8000;

        location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot|html)$ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
            proxy_pass http://$backend_upstream;
        }

        location / {
            limit_req zone=api_limit nodelay;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
            proxy_pass http://$backend_upstream;

            client_max_body_size 2M;
        }

        location /main-service/v1/auth/login {
            limit_req zone=login_limit burst=2 nodelay;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://$backend_upstream;

            client_max_body_size 2M;
        }
    }
}
