# Generated by Django 5.2.11 on 2026-08-31 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=32, verbose_name='Endpoint')),
                ('key', models.CharField(max_length=64, verbose_name='Idempotency Key')),
                ('request_fingerprint', models.CharField(max_length=64, verbose_name='Request Fingerprint')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=16, verbose_name='Status')),
                ('response_body', models.JSONField(blank=True, null=True, verbose_name='Stored Response')),
                ('reference', models.CharField(blank=True, max_length=64, verbose_name='Reference')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='Correlation ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Idempotency Record',
                'verbose_name_plural': 'Idempotency Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='idem_created_at_idx'), models.Index(fields=['status', 'created_at'], name='idem_status_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'endpoint', 'key'), name='uniq_idempotency_user_endpoint_key')],
            },
        ),
    ]
