FROM python:3.12-slim-bookworm


ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1


RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser


WORKDIR /app


RUN mkdir -p /app/users-data && \
    chown -R appuser:appgroup /app


COPY --chown=appuser:appgroup requirements.txt .


RUN pip install --no-cache-dir -i https://mirror-pypi.runflare.com/simple --upgrade pip && \
    pip install --no-cache-dir -i https://mirror-pypi.runflare.com/simple -r requirements.txt


COPY --chown=appuser:appgroup . .


USER appuser


EXPOSE 8000


CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]