# Generated by Django 5.2.11 on 2026-04-10 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preregister', 'PreRegister'), ('suspended', 'Suspended'), ('authenticated', 'Authenticated')], default=('preregister', 'PreRegister'), max_length=50, verbose_name='Status')),
                ('level', models.CharField(choices=[('br', 'Boronze'), ('si', 'Silver'), ('go', 'Gold')], default=('br', 'Boronze'), max_length=50, verbose_name='Level')),
                ('referral_code', models.CharField(blank=True, max_length=12, verbose_name='Referral Code')),
                ('used_referral_code', models.CharField(blank=True, max_length=12, verbose_name='Used Referral Code')),
                ('birth_date', models.CharField(default='-', max_length=10, verbose_name='Birthday')),
                ('sex', models.CharField(choices=[('unknown', '?'), ('male', 'Male'), ('female', 'Female')], default=('unknown', '?'), max_length=50, verbose_name='Sex')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('gov_verified', 'Gov Verified'), ('document_uploaded', 'Document Uploaded'), ('pending_review', 'Pending Review'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='not_started', max_length=30)),
                ('government_verified', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='customers.customer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.siteadmin')),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYCs',
            },
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('national_card', 'National Card')], max_length=30)),
                ('image_url', models.URLField(verbose_name='Image Url')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.kyc')),
            ],
        ),
    ]
