# Generated by Django 5.2.11 on 2026-04-13 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_siteadmin_profile_pic'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, verbose_name='Bank Name')),
                ('card_number', models.CharField(max_length=16, verbose_name='Card Number')),
                ('account_number', models.CharField(default='-', max_length=30, verbose_name='Account Number')),
                ('Shaba_number', models.CharField(default='-', max_length=50, verbose_name='Shaba Number')),
                ('is_verifed', models.BooleanField(default=None, null=True, verbose_name='Is Verified')),
                ('card_ownership', models.BooleanField(default=False, verbose_name='Ownership')),
                ('owner_information', models.BooleanField(default=False, verbose_name='Owner Information')),
                ('is_show', models.BooleanField(default=True, verbose_name='Show To Customer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('ownership_counter', models.IntegerField(default=0, verbose_name='Ownership Counter')),
                ('information_counter', models.IntegerField(default=0, verbose_name='Information Counter')),
                ('check_again_on', models.DateTimeField(verbose_name='Check On')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='customers.customer')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.siteadmin', verbose_name='Modified By')),
            ],
        ),
    ]
