# Generated by Django 5.2.11 on 2026-04-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_bankcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcard',
            name='is_verifed',
        ),
        migrations.AddField(
            model_name='bankcard',
            name='is_verified',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Is Verified'),
        ),
    ]
