# Generated by Django 5.2.11 on 2026-04-13 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_siteadmin_profile_pic'),
        ('customers', '0003_remove_bankcard_is_verifed_bankcard_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='is_verified',
            field=models.BooleanField(default=None, null=True, verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.siteadmin', verbose_name='Modified By'),
        ),
    ]
