# Generated by Django 5.2.11 on 2026-04-16 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_siteadmin_profile_pic'),
        ('customers', '0004_alter_bankcard_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncreaseDailyGoldLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Amount')),
                ('limit_type', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy')], default='Other', max_length=10, verbose_name='Limit Type')),
                ('is_verifid', models.BooleanField(default=None, null=True, verbose_name='Is Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.siteadmin', verbose_name='Modified By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Customer')),
            ],
        ),
    ]
