# Generated by Django 5.2.11 on 2026-05-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_increasedailytransactionlimit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='government_verified',
            new_name='shahkar_check',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sex',
        ),
        migrations.AddField(
            model_name='customer',
            name='father_name',
            field=models.CharField(blank=True, default='Adam', max_length=25),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('unknown', '?'), ('male', 'Male'), ('female', 'Female')], default='unknown', max_length=7, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.CharField(choices=[('br', 'Boronze'), ('si', 'Silver'), ('go', 'Gold')], default='br', max_length=50, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('preregister', 'PreRegister'), ('suspended', 'Suspended'), ('authenticated', 'Authenticated')], default='preregister', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('shahkar_verified', 'Shahkar Verified'), ('identity_verified', 'Identity Verified'), ('pending_upload', 'Pending Upload'), ('pending_review', 'Pending Review'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='not_started', max_length=30),
        ),
    ]
