# Generated by Django 5.2.11 on 2026-05-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_rename_government_verified_kyc_shahkar_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='image_url',
            field=models.URLField(max_length=1000, verbose_name='Image Url'),
        ),
    ]
