# Generated by Django 5.2.11 on 2026-05-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_kycdocument_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Reject Reason'),
        ),
    ]
