# Generated by Django 5.2.11 on 2026-04-10 14:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(default='New', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(default='User', max_length=50, verbose_name='Last Name')),
                ('phone_number', models.CharField(default='-', max_length=11, unique=True, verbose_name='Phone Number')),
                ('national_id', models.CharField(default='-', max_length=10, verbose_name='National ID')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Is Suspended')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Last Login')),
                ('last_ip_address', models.GenericIPAddressField(default='0.0.0.0', verbose_name='Last Ip Address')),
                ('is_2fa_enabled', models.BooleanField(default=False, verbose_name='Is 2FA Enabled')),
                ('requires_2fa', models.BooleanField(default=False, verbose_name='Requires 2FA')),
                ('totp_secret', models.CharField(blank=True, max_length=32, verbose_name='2FA Secret')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'unique_together': {('phone_number', 'national_id')},
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
