# Generated by Django 5.2.11 on 2026-04-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Project', max_length=100, verbose_name='Site Name')),
                ('customer_register', models.BooleanField(default=True, verbose_name='Customer Register')),
                ('customer_login', models.BooleanField(default=True, verbose_name='Customer Login')),
                ('check_mobile_ownership', models.BooleanField(default=False, verbose_name='Check Mobile Ownership')),
                ('send_welcome_sms', models.BooleanField(default=False, verbose_name='Send Welome Message')),
                ('send_login_alert_sms', models.BooleanField(default=False, verbose_name='Send Login Alret SMS')),
                ('modified_timestamp', models.IntegerField(default=0, verbose_name='Modified Timestamp')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Setting',
            },
        ),
    ]
