# Generated by Django 5.2.11 on 2026-04-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='is_buy',
            field=models.BooleanField(default=False, verbose_name='Buy Is Enabled'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='is_sell',
            field=models.BooleanField(default=False, verbose_name='Sell Is Enabled'),
        ),
    ]
