# Generated by Django 5.2.11 on 2026-05-14 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0009_bankcard_reject_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0, verbose_name='Amount')),
                ('remaining_wallet_amount', models.BigIntegerField(default=0, verbose_name='Remaining Wallet Amount')),
                ('wallet_balance', models.BigIntegerField(default=0, verbose_name='Wallet Balance')),
                ('settlement_method', models.CharField(max_length=50, verbose_name='Settlement Method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent_to_bank', 'Sent To Bank'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30, verbose_name='Status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('bank_send', models.BooleanField(default=False, verbose_name='Sent To Bank')),
                ('is_instant', models.BooleanField(default=False, verbose_name='Is Instant')),
                ('inquiry_check', models.BooleanField(default=False, verbose_name='Inquiry Checked')),
                ('reject_reason', models.CharField(blank=True, max_length=255, verbose_name='Reject Reason')),
                ('desc', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('wage', models.IntegerField(default=0, verbose_name='Wage')),
                ('vandar_amount', models.BigIntegerField(default=0, verbose_name='Vandar Amount')),
                ('vandar_status', models.CharField(blank=True, max_length=50, verbose_name='Vandar Status')),
                ('track_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Track ID')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Transaction ID')),
                ('iban', models.CharField(blank=True, max_length=255, verbose_name='IBAN')),
                ('iban_id', models.CharField(blank=True, max_length=255, verbose_name='IBAN ID')),
                ('settlement_date', models.CharField(blank=True, max_length=20, verbose_name='Settlement Date')),
                ('settlement_time', models.CharField(blank=True, max_length=20, verbose_name='Settlement Time')),
                ('process_time', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='Errors')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='customers.bankcard', verbose_name='Bank Card')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='settlements_status_cf9f64_idx'), models.Index(fields=['created_at'], name='settlements_created_778d49_idx'), models.Index(fields=['customer'], name='settlements_custome_116711_idx'), models.Index(fields=['transaction_id'], name='settlements_transac_0a69a1_idx'), models.Index(fields=['track_id'], name='settlements_track_i_d1162c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='withdrawal_amount_gte_0'), models.CheckConstraint(condition=models.Q(('wage__gte', 0)), name='withdrawal_wage_gte_0'), models.CheckConstraint(condition=models.Q(('wallet_balance__gte', 0)), name='wallet_balance_gte_0')],
            },
        ),
    ]
