# Generated by Django 5.2.11 on 2026-08-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0002_alter_withdrawal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='last_inquiry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Inquiry At'),
        ),
    ]
